import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

const mockResponses: Record<string, (prompt: string, market: string, timeframe: string) => string> = {
  signal_generator: (prompt, market, timeframe) => `
## ${market.toUpperCase()} Signal — ${timeframe.toUpperCase()}

**Direction:** BUY  
**Confidence:** 87%  
**Setup:** Breakout + Volume Confirmation  

### Entry Parameters
- **Entry Zone:** 1.0850 – 1.0860
- **Stop Loss:** 1.0825 (-25 pips)
- **Take Profit 1:** 1.0890 (+30 pips, 1:1.2 R/R)
- **Take Profit 2:** 1.0920 (+60 pips, 1:2.4 R/R)

### Technical Confluence
1. Price broke above 20-day EMA with 1.5x average volume
2. RSI(14) at 58 — room to run before overbought (>70)
3. MACD histogram turning positive on ${timeframe} timeframe
4. Support held at previous swing low (1.0830) — 2 touches confirmed

### Risk Management
- **Position Size:** 0.5% risk per trade
- **Max Drawdown Allowance:** 2% daily limit reached = stop for session
- **Correlation Check:** Avoid simultaneous EUR and GBP exposure

### Invalidation
Close below 1.0820 on 4H candle invalidates the setup. Re-assess bias.

---
Generated by AlphaDraft AI | Backtested on last 100 similar setups: 62% win rate
`,

  risk_analysis: (prompt, market) => `
## Portfolio Risk Analysis — ${market.toUpperCase()}

### Current Exposure
| Pair | Direction | Size | Risk % | Correlation |
|------|-----------|------|--------|-------------|
| EURUSD | Long | 1.0 lot | 0.5% | Base |
| GBPUSD | Long | 0.5 lot | 0.3% | +0.85 corr |
| USDJPY | Short | 0.75 lot | 0.4% | Hedge |

**Total Portfolio Heat:** 1.2% at risk  
**Correlation Risk:** HIGH — EUR and GBP moving together amplifies USD downside exposure

### Scenario Stress Test
| Scenario | Portfolio Impact | Probability |
|----------|-----------------|-------------|
| DXY +1.0% | -2.1% portfolio | 22% |
| NFP beat +50k | -0.8% portfolio | 35% |
| FOMC hawkish pause | -1.5% portfolio | 18% |

### Recommendations
1. **Reduce GBP exposure** to 0.25 lot — correlation drag too high
2. **Add CHF hedge** — negative correlation to EUR during risk-off
3. **Tighten EURUSD stop** to 1.0840 — upcoming ECB speech volatility

### Kelly Criterion Sizing
Optimal bet size for current edge (assumed 55% win rate, 1.5:1 R/R):  
**f* = 0.083 → Use 1/4 Kelly = 2.08% max risk per trade**

---
AlphaDraft Risk Engine | VaR(95%) calculated over 30-day rolling window
`,

  position_sizing: (prompt, market) => `
## Position Size Calculator — ${market.toUpperCase()}

### Inputs
- **Account Balance:** $10,000
- **Risk Per Trade:** 1.0%
- **Entry:** 1.0850
- **Stop Loss:** 1.0820 (-30 pips)
- **Take Profit:** 1.0910 (+60 pips)
- **R/R Ratio:** 1:2.0

### Calculation
\`\`\`
Risk Amount = $10,000 × 1.0% = $100
Pip Value (EURUSD) = $10 per pip per standard lot
Risk in Pips = 30
Position Size = $100 ÷ (30 pips × $10/pip) = 0.33 standard lots
\`\`\`

**Trade Size: 0.33 lots (3.3 mini lots / 33 micro lots)**

### Scaling Plan
| Stage | Size | Trigger | R-Multiple Target |
|-------|------|---------|-------------------|
| 1 | 0.33 lot | Initial entry | +1R |
| 2 | +0.17 lot | TP1 hit, move to BE | +2R total |
| 3 | +0.17 lot | Breakout continuation | +3R total |

### Advanced: Fixed Fractional vs Fixed Ratio
- **Fixed Fractional (current):** Risk 1% flat — slower growth, lower drawdown
- **Fixed Ratio:** Increase size every +$2,000 profit — faster growth, higher variance
- **Optimal for this edge:** Fixed Fractional until 20% account growth, then switch

### Warning
If consecutive losses = 3, reduce risk to 0.5% until 2 consecutive wins.  
This preserves capital during regime change (choppy → trending).

---
AlphaDraft Position Engine | Never risk more than you can afford to lose
`,

  market_report: (prompt, market) => `
## ${market.toUpperCase()} Market Intelligence Report

**Date:** ${new Date().toLocaleDateString()}  
**Bias:** Bullish (Short-Term) | Neutral (Medium-Term)  
**Volatility Regime:** Expanding (ATR +12% vs 20-day average)

### Macro Drivers
1. **Fed Policy:** Dovish repricing post-CPI miss — DXY weakness supports ${market} upside
2. **ECB:** Lagarde hawkish rhetoric at Sintra — EUR support
3. **Geopolitical:** Middle East tensions → oil bid → inflation sticky → rates higher for longer

### Technical Landscape
- **Trend:** Higher highs, higher lows on daily — intact bull structure
- **Key Levels:**
  - Resistance: 1.0950 (psychological), 1.1020 (yearly high)
  - Support: 1.0800 (200 DMA), 1.0750 (previous breakout level)
- **Pattern:** Ascending triangle forming on 4H — measured move +150 pips

### Institutional Flow
- COT Report: Asset managers increased long exposure by +8,400 contracts
- Options market: 1.0900 calls seeing unusual volume — gamma wall at 1.0950

### AI Bias Forecast
| Timeframe | Direction | Confidence | Catalyst Needed |
|-----------|-----------|------------|-----------------|
| 1H | Long | 72% | Hold above 1.0830 |
| 4H | Long | 65% | Volume on breakout |
| Daily | Neutral | 54% | Await ECB/Fed clarity |

### Trade Plan
**If** price holds 1.0830 into London open → **Then** long targeting 1.0900  
**Else** if 1.0800 breaks → **Then** flip short to 1.0750

---
AlphaDraft Market Intelligence | Data-driven, not opinion-driven
`,

  backtest_logic: (prompt, market, timeframe) => `
## Strategy Backtest Logic — ${timeframe.toUpperCase()} ${market.toUpperCase()}

### Strategy Rules
**Entry:** 20 EMA cross above 50 EMA + RSI > 50 + Volume > 1.2x average  
**Exit:** 20 EMA cross below 50 EMA OR trailing ATR(14) × 2  
**Filter:** No trades during high-impact news (NFP, FOMC, CPI)

### Pseudo-Code
\`\`\`
IF (ema20 > ema50) AND (rsi > 50) AND (volume > avg_volume * 1.2)
   AND (news_impact < 3) THEN
   ENTER_LONG()
   stop_loss = lowest_low(10)
   take_profit = entry + (entry - stop_loss) * 2
   trail_stop = atr(14) * 2
END IF
\`\`\`

### Backtest Results (Simulated 2020–2024)
| Metric | Value | Benchmark (Buy & Hold) |
|--------|-------|------------------------|
| Total Trades | 284 | — |
| Win Rate | 58.4% | — |
| Profit Factor | 1.72 | — |
| Net Profit | +142% | +38% |
| Max Drawdown | -18.3% | -34% |
| Sharpe Ratio | 1.45 | 0.62 |
| Recovery Factor | 7.8 | 1.1 |

### Equity Curve Analysis
- **Q1 2022:** Underperformed (-12%) — choppy regime, whipsaws on EMA crosses
- **Q2–Q3 2022:** Outperformed (+45%) — strong trending phase, trailing stops captured extended moves
- **2023:** Flat (+3%) — low volatility, reduced signal quality

### Optimization Insights
1. **Best timeframe:** 4H (higher win rate than 1H, fewer false signals than Daily)
2. **Best session:** London–NY overlap (08:00–12:00 EST) — 68% of profits generated
3. **Worst month:** August (summer doldrums) — consider reducing size by 50%

### Forward Test Checklist
- [ ] Paper trade for 30 trades minimum
- [ ] Compare live fills to backtest assumptions (slippage, spread)
- [ ] Monitor win rate — if < 52% over 50 trades, strategy degraded

---
AlphaDraft Backtest Engine | Past performance does not guarantee future results
`,

  trade_plan: (prompt, market, timeframe) => `
## Complete Trade Plan — ${market.toUpperCase()} ${timeframe.toUpperCase()}

### Pre-Market Preparation
1. **Economic Calendar Check:** No high-impact news in next 4 hours
2. **Overnight Levels:** Asian session high/low marked, volume profile analyzed
3. **Correlation Matrix:** EUR/GBP at +0.85 — avoid simultaneous exposure
4. **Mental State:** Rested, no FOMO from missed moves yesterday

### Trade Setup
| Parameter | Value | Rationale |
|-----------|-------|-----------|
| Pair | EURUSD | Strongest trend on daily |
| Direction | Long | Breakout + volume confirmation |
| Entry | 1.0850 | Pullback to 20 EMA |
| Stop Loss | 1.0820 | Below swing low, -30 pips |
| Take Profit 1 | 1.0890 | 1:1 R/R, partial close |
| Take Profit 2 | 1.0920 | 1:2 R/R, trail remaining |
| Position Size | 0.33 lot | 1% risk on $10k account |

### Execution Checklist
- [ ] Price touches 1.0850 zone
- [ ] 5-min candle closes bullish (hammer or engulfing)
- [ ] Volume > 1.2x 20-period average
- [ ] Spread < 1.5 pips (avoid news spikes)
- [ ] Set alarm for 1.0870 (breakeven move)

### Contingency Plans
| Scenario | Action |
|----------|--------|
| Price reverses before entry | Cancel order, reassess at next session |
| Stop loss hit | Log trade, review setup. No revenge trading |
| TP1 hit, price stalls | Move stop to breakeven, hold for TP2 |
| Unexpected news (NFP leak) | Close 50% immediately, trail rest |

### Post-Trade Review
- **If win:** What worked? Can this be systematized?
- **If loss:** Was setup valid? Was risk managed? Any emotional deviation?
- **Journal entry required within 30 minutes**

---
AlphaDraft Trade Plan Engine | Plan the trade, trade the plan
`,
}

Deno.serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    const authHeader = req.headers.get('Authorization')
    if (!authHeader) throw new Error('No auth header')

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL')!,
      Deno.env.get('SUPABASE_ANON_KEY')!,
      { global: { headers: { Authorization: authHeader } } }
    )

    const { data: { user }, error: userError } = await supabase.auth.getUser()
    if (userError || !user) throw new Error('Unauthorized')

    const { data: profile } = await supabase
      .from('profiles')
      .select('monthly_credits_used, monthly_credits_limit, subscription_tier')
      .eq('id', user.id)
      .single()

    if (!profile) throw new Error('Profile not found')
    if (profile.monthly_credits_used >= profile.monthly_credits_limit) {
      return new Response(
        JSON.stringify({ error: 'Credit limit exceeded. Upgrade to Pro.' }),
        { status: 429, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      )
    }

    const { prompt, strategy_type, market, timeframe, settings } = await req.json()

    const mkt = market || 'forex'
    const tf = timeframe || 'day'
    const type = strategy_type || 'signal_generator'

    const content = mockResponses[type]?.(prompt, mkt, tf) || mockResponses.signal_generator(prompt, mkt, tf)

    await supabase
      .from('profiles')
      .update({ monthly_credits_used: profile.monthly_credits_used + 1 })
      .eq('id', user.id)

    await supabase.from('usage_logs').insert({
      user_id: user.id,
      action: 'generate',
      metadata: { strategy_type: type, market: mkt, timeframe: tf, model: 'mock-alpha-v1' }
    })

    return new Response(
      JSON.stringify({ 
        content, 
        tokens_used: Math.floor(content.length / 4), 
        credits_remaining: profile.monthly_credits_limit - profile.monthly_credits_used - 1,
        confidence_score: Math.floor(Math.random() * 30) + 70
      }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )

  } catch (error: any) {
    return new Response(
      JSON.stringify({ error: error.message }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    )
  }
})